services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - 8191:8191
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8191"]
      interval: 30s
      retries: 5
      start_period: 3s
      timeout: 10s

  manganotifierr:
    build: .
    tty: true
    init: true
    volumes:
      - ./data:/data
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      FLARESOLVERR_HOST: flaresolverr
      FLARESOLVERR_PORT: 8191
      LIBRARY_PATH: /data/library
      DATABASE_PATH: /data/db.sqlite
    depends_on:
      flaresolverr:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - path: ./src
          action: rebuild
          target: /app
