services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest

  manganotifierr:
    build: .
    volumes:
      - ./data:/data
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}

